spring.application.name=FirstSecurity1

#change the username and password of spring security by default
#only one user for one application
#spring.security.user.name=aditya
#spring.security.user.password=pass123